<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BufferStreamPackageVersion Condition="'$(BufferStreamPackageVersion)' == ''">1.0.0</BufferStreamPackageVersion>
    <RestoreAdditionalProjectSources>$(MSBuildThisFileDirectory)..\..\artifacts\packages</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BufferStream" Version="$(BufferStreamPackageVersion)" />
  </ItemGroup>

</Project>
